apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: bigdata
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
    - name: controller
      port: 9093

